<?php
$CONFIG = array(
  'enable_previews' => true,
  'enabledPreviewProviders' => array(
    'OC\\Preview\\AVI',
    'OC\\Preview\\BMP',
    'OC\\Preview\\Font',
    'OC\\Preview\\GIF',
    'OC\\Preview\\Illustrator',
    'OC\\Preview\\Image',
    'OC\\Preview\\JPEG',
    'OC\\Preview\\MarkDown',
    'OC\\Preview\\MKV',
    'OC\\Preview\\Movie',
    'OC\\Preview\\MP4',
    'OC\\Preview\\MSOffice',
    'OC\\Preview\\MSOffice2003',
    'OC\\Preview\\MSOffice2007',
    'OC\\Preview\\MSOfficeDoc',
    'OC\\Preview\\OpenDocument',
    'OC\\Preview\\PDF',
    'OC\\Preview\\Photoshop',
    'OC\\Preview\\PNG',
    'OC\\Preview\\SGI',
    'OC\\Preview\\SVG',
    'OC\\Preview\\TGA',
    'OC\\Preview\\TIFF',
    'OC\\Preview\\TXT',
    'OC\\Preview\\XBitmap',
),
);
